name: 'Skip CI action'
author: 'Legorooj'
description: 'A GitHub action to skip CI when the commit message contains [skip ci] (or another RegEx pattern)'
icon: fast-forward
inputs:
    pattern:
        description: 'The RegEx pattern to search the commit message for'
        required: true
        default: '(\[skip[\s\-](ci|actions|ga)|(ci|actions|ga)[\s\-]skip\])'
    token:
        description: 'The GitHub token used to authenticate requests to the GitHub API.'
        default: '${{ github.token }}'
outputs:
    canSkip:
        description: 'Whether or not your action should skip'
runs:
    using: 'node12'
    main: 'index.js'
